// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXlBgKsxLOshHCoch9KtSTS2uY-GltYs',
    appId: '1:599522831280:web:189f8b309d92fd5f768475',
    messagingSenderId: '599522831280',
    projectId: 'zync-5c338',
    authDomain: 'zync-5c338.firebaseapp.com',
    storageBucket: 'zync-5c338.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbqgTZWEOkmbG0LHGf8rIrs_aUn_vBjwE',
    appId: '1:599522831280:android:e1633eebea0e30bd768475',
    messagingSenderId: '599522831280',
    projectId: 'zync-5c338',
    storageBucket: 'zync-5c338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjDlx06CvQygCLDeXmrC6Utpg5rHjqPw',
    appId: '1:599522831280:ios:66b0b1e87c05c898768475',
    messagingSenderId: '599522831280',
    projectId: 'zync-5c338',
    storageBucket: 'zync-5c338.firebasestorage.app',
    iosBundleId: 'com.example.miRedSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjDlx06CvQygCLDeXmrC6Utpg5rHjqPw',
    appId: '1:599522831280:ios:66b0b1e87c05c898768475',
    messagingSenderId: '599522831280',
    projectId: 'zync-5c338',
    storageBucket: 'zync-5c338.firebasestorage.app',
    iosBundleId: 'com.example.miRedSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtXlBgKsxLOshHCoch9KtSTS2uY-GltYs',
    appId: '1:599522831280:web:4979e75c786ab55e768475',
    messagingSenderId: '599522831280',
    projectId: 'zync-5c338',
    authDomain: 'zync-5c338.firebaseapp.com',
    storageBucket: 'zync-5c338.firebasestorage.app',
  );
}
